openapi: 3.0.0
paths:
  /health:
    get:
      operationId: AppController_getHealth
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
info:
  title: Customers Microservice
  description: RestAPI For Customers Microservice
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas: {}
