openapi: 3.0.0
paths:
  /health:
    get:
      operationId: AppController_healthCheck
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
info:
  title: Models MS RestAPI
  description: MS used to manage LLMs
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas: {}
